export const Dummydata = [
  {
    id: "1",
    title: "Alumni Membership Form Template",
    owner: "Jane",
    body: "What is Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book it has?",
    creation_date: "6321556432",
    link: "https://formpl.us.com",
  },
  {
    id: "2",
    title: "Alumni Membership Form Template",
    owner: "Jane",
    body: "What is Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book it has?",
    creation_date: "6321556432",
    link: "https://formpl.us.com",
  },
  {
    id: "3",
    title: "Alumni Membership Form Template",
    owner: "Jane",
    body: "What is Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book it has?",
    creation_date: "6321556432",
    link: "https://formpl.us.com",
  },
  {
    id: "4",
    title: "Alumni Membership Form Template",
    owner: "Tom",
    body: "What is Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book it has?",
    creation_date: "6321556432",
    link: "https://formpl.us.com",
  },
  {
    id: "5",
    title: "Alumni Membership Form Template",
    owner: "Tom",
    body: "What is Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book it has?",
    creation_date: "6321556432",
    link: "https://formpl.us.com",
  },
  {
    id: "6",
    title: "Alumni Membership Form Template",
    owner: "Sharon",
    body: "What is Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book it has?",
    creation_date: "6321556432",
    link: "https://formpl.us.com",
  },
  {
    id: "7",
    title: "Alumni Membership Form Template",
    owner: "Jane",
    body: "What is Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book it has?",
    creation_date: "6321556432",
    link: "https://formpl.us.com",
  },
  {
    id: "8",
    title: "Alumni Membership Form Template",
    owner: "Jane",
    body: "What is Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book it has?",
    creation_date: "6321556432",
    link: "https://formpl.us.com",
  },
  {
    id: "9",
    title: "Alumni Membership Form Template",
    owner: "Jane",
    body: "What is Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book it has?",
    creation_date: "6321556432",
    link: "https://formpl.us.com",
  },
  {
    id: "10",
    title: "Alumni Membership Form Template",
    owner: "Tom",
    body: "What is Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book it has?",
    creation_date: "6321556432",
    link: "https://formpl.us.com",
  },
  {
    id: "11",
    title: "Alumni Membership Form Template",
    owner: "Tom",
    body: "What is Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book it has?",
    creation_date: "6321556432",
    link: "https://formpl.us.com",
  },
  {
    id: "12",
    title: "Alumni Membership Form Template",
    owner: "Sharon",
    body: "What is Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book it has?",
    creation_date: "6321556432",
    link: "https://formpl.us.com",
  },
];
